name: Changeset Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changeset-check:
    name: Check for Changesets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Check for changesets
        run: |
          # Skip changeset check for automated version PRs
          if [[ "${{ github.head_ref }}" == "changeset-release/"* ]]; then
            echo "Skipping changeset check for automated release PR"
            exit 0
          fi

          # Run changeset status to check if there are any changesets
          npm run changeset:status || {
            echo "::error::No changeset found. Please add a changeset by running 'npm run changeset' and commit the result."
            echo "::error::If this PR doesn't require a release (e.g., docs, tests, or build tools only), run 'npm run changeset -- --empty' to create an empty changeset."
            exit 1
          }
